= Bienvenue à "Technologies digitales et ruptures business"
== 1. Buts de ce module

- Rencontre "culturelle" de la tech et du business

-> Maîtriser les notions essentielles, le vocabulaire même, en technologie.

-> Donner à voir certains changements techno-sociaux (2005 - 2015) qui ont rendus ces technos essentielles

-> Illustrer par le CRM

- Pour rendre possible l'action managériale à dimension technologique

-> Avec Guillaume Lecuyer, Direceur Marketing chez Visiativ, apprendre à formuler un projet technologique "disruptif" dans son organisation.

Comment donner un panorama des technologies disruptives et ruptures business en 3 jours, tout en conservant du temps pour des témoignages et du travail de groupe?

Un socle commun: la data

- C'est le matériau commun aux innovations que l'on voit aujourd'hui.

En un mot: les innovations autour de la donnée sont aux sources ou accélèrent l'innovation dans les technologies "hardware" ou applicative que sont l'IoT, la robotique, la blockchain, ...

- Un(e) manager avec une excellente compréhension de la data et de ses enjeux business est équipé(e) conceptuellement pour mener un projet de création de valeur dans l'entreprise.

- Il reste la mise en oeuvre, la conduite du changement... ce sont les modules suivants.

== 2. Programme

==== Jour 1

- Matin: notions fondamentales: data, big data, apis.
- Après-midi: focus sur l'Internet des Objets (IoT): au croisement de l'objet et de la donnée

==== Jour 2

- Matin: l'exemple du CRM "disrupté". Présentations sur aspects technos et techs
- Après-midi: visite d'entreprise qui vit sa TDO.

==== Jour 3

- Matin: de la data à l'IA, débuts du travail sur projets
- Après-midi: travaux sur projets: comment valoriser la donnée dans mon entreprise


== 3. S'appuyer sur vos compétences, échanger les expériences

Ce cours organise une rencontre entre deux thématiques fortes que sont les techs et le business.

Vous avez de fortes expériences sur ces deux axes.

Le matin du deuxième jour en deuxième partie, nous allons apprendre dans ces deux directions.

L'idée est de prendre un cas que vous connaissez bien et qui vous a frappé.

Côté business, décrivez:

- *les enjeux business* (croissance? changement dans la chaîne de valeur? structure de coûts?)
- d'une innovation / d'un changement techno
- dans votre industrie / chez vos concurrents / en interne / qui a une pertinence pour votre périmètre.

Exemples: l'arrivée d'un concurrent 100% digital, l'évolution des processus de production ou de distribution.

Côté tech, décrivez:

- *les enjeux technologiques*
- d'une innovation simple *liée à la data*
- dans votre industrie / chez vos concurrents / qui a une pertinence pour votre périmètre.

Exemples: une techno très ciblée comme les DMP, ou un type d'algorithme, un logiciel...

Format:

- 8 minutes (vraiment minutées)
- sans slides


<<<
