= Week 3 - CRMs and segmentation
== 1. Clarifications

Register your groups in the spreadsheet - address is in the group project description on Brightspace.

On finding a topic / interviewee:

- write it in the spreadsheet
- don't start late!
- doubts? Problems? Email me, visit during office hours (Tuesday mornings) or by appointment.

Quizzes: there is no "auto-grading".

As written in the syllabus, I will compute the grade by sampling 3 quizzes out of the 9 you'll take.

== 2. Let's discuss key aspects of the content of the lecture for today

1. on CRMs:

- you must be aware of the challenges and opportunities of data driven crms

(in particular, you should understand how a DMP and a CRMs are distinct but overlap)

*and*

- not fall in the trap of thinking bigger software / data scientists will solve a marketing problem.


[start=2]
2. on segmentation:

- you must be able to understand what "clustering" means.

- you must understand the principles of k-means and hierarchical clustering



<<<
